### PR TITLE
Hf datum tokenizer

### PR DESCRIPTION
**Pull request by jmbarne3**
Upgraded the typeahead version to get around a bug in the 0.11.1 library. In addition, added js sorting logic.

### CODE REVIEW

**Comment by keeeeeegan** [comment]
Good

**Comment by cjg89** [comment]
Good!

**Comment by rjucf** [comment]
It would be good to cache $('.tt-input') outside the addScore function if addScore is called multiple times:
https://github.com/UCF/UCF-Degree-Search-Plugin/pull/4/files#diff-38557cfead54a76836190fd45bdd2460R20

**Comment by jmbarne3** [comment]
Per RJ: Ignoring his comment. 👍

**Pull request merged**
